[workspace]
members = ["game", "common-rs", "toybox-rs", "toy-rs"]



[patch."https://github.com/manpat/common-rs.git"]
common = { path = "common-rs" }

[patch."https://github.com/manpat/toy-rs.git"]
toy = { path = "toy-rs" }


