[package]
name = "common"
version = "1.0.0"
edition = "2021"
authors = ["Patrick Monaghan <0x5f.manpat@gmail.com>"]

[dependencies]
rand = "0.8"
rand_derive2 = "0.1"

serde = { version="1.0", features=["derive"], optional=true }


[features]
serde = ["dep:serde"]